# time: 09/09/2021
# update: /
# author: Bobby
# We defined the obstacles in the environment line by line.

None:
  - []
Easy:
  - [[5.,6.], [5.,4.]]
Medium: 
  - [[5.,6.], [5.,4.]]
  - [[4.,5.], [6.,5.]]
Hard:
  - [[1.5,5.5],[4.5,5.5]]
  - [[5.5,5.5],[7.5,5.5]]
  - [[1.5,4.5],[4.5,4.5]]
  - [[5.5,4.5],[7.5,4.5]]
  - [[4.5,5.5],[4.5,7.5]]
  - [[5.5,5.5],[5.5,7.5]]
  - [[4.5,4.5],[4.5,1.5]]
  - [[5.5,4.5],[5.5,1.5]]