# time: 09/09/2021
# update: /
# author: Bobby
# We defined the obstacles in the environment line by line.

None:
  - []
Easy:
  - [[5.,7.], [5.,3.]]
Medium: 
  - [[5.,7.], [5.,3.]]
  - [[3.,5.], [7.,5.]]
Hard:
  - [[1.5,5.5],[4.5,5.5]]
  - [[5.5,5.5],[8.5,5.5]]
  - [[1.5,4.5],[4.5,4.5]]
  - [[5.5,4.5],[8.5,4.5]]
  - [[4.5,5.5],[4.5,8.5]]
  - [[5.5,5.5],[5.5,8.5]]
  - [[4.5,4.5],[4.5,1.5]]
  - [[5.5,4.5],[5.5,1.5]]